name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build cpplint image
        run: docker build cpplint/ -t cpplint
      - name: Check code in /src
        run: docker run -v ${PWD}:/app cpplint bash -c "find src/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
      - name: Check code in /unit_tests
        run: docker run -v ${PWD}:/app cpplint bash -c "find unit_tests/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"

  build:
    runs-on: ubuntu-latest
    needs: cpplint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{github.repository}}:latest
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar

  unit_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp/
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a
      - name: Run tests
        run: docker run ${{github.repository}} reduct-tests

  api_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp/
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a
      - name: Build API tests
        run: docker build -t api_tests ./api_tests
      - name: Run Storage
        run: docker run --network=host -d ${{github.repository}}
      - name: Run API tests
        run: docker run --network=host api_tests